# Generated by Django 4.2.23 on 2025-09-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='option_d',
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='correct_answer',
            field=models.TextField(),
        ),
    ]
