# Generated by Django 4.2.23 on 2025-09-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='expected_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('open_ended', 'Open Ended')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='sample_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
