# Generated by Django 4.2.7 on 2025-09-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamsession',
            name='notes',
            field=models.TextField(blank=True, help_text='JSON data for adaptive session and other metadata', null=True),
        ),
    ]
