# Generated by Django 4.2.23 on 2025-07-19 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='phone',
            field=models.CharField(default='000-000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(default='Mathematics', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='000-000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(default='Mathematics', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty_estimate', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
