# Generated by Django 4.2.23 on 2025-09-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_questionbank_expected_keywords_and_more'),
        ('scheduler', '0002_remove_questionbank_option_a_and_more'),
    ]

    operations = [
    ]
