# Generated by Django 4.2.23 on 2025-09-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_questionbank_expected_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.TextField(),
        ),
    ]
