# Generated by Django 4.2.7 on 2025-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_studentexamsession_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamanswer',
            name='partial_score',
            field=models.FloatField(default=0.0, help_text='Score from 0.0 to 1.0 for partial credit'),
        ),
    ]
