# Generated by Django 4.2.23 on 2025-07-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_lesson_end_time_remove_lesson_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
