# Generated by Django 4.2.23 on 2025-09-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_merge_20250925_2000'),
        ('scheduler', '0003_studentanswer_score_alter_studentanswer_answer'),
    ]

    operations = [
    ]
