# Generated by Django 4.2.7 on 2025-09-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_studentexamanswer_partial_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveexamquestion',
            name='numeric_solution',
            field=models.TextField(blank=True, help_text='Numeric solution with tolerance (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='interactiveexamquestion',
            name='pass_mark',
            field=models.IntegerField(default=60, help_text='Minimum score to pass (0-100)'),
        ),
        migrations.AddField(
            model_name='interactiveexamquestion',
            name='rubric',
            field=models.TextField(blank=True, help_text='Grading rubric with key points and weights (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='studentexamanswer',
            name='correctness',
            field=models.CharField(default='unknown', help_text='correct/partial/incorrect', max_length=20),
        ),
        migrations.AddField(
            model_name='studentexamanswer',
            name='feedback',
            field=models.TextField(blank=True, help_text='Gemini feedback in Hebrew', null=True),
        ),
        migrations.AddField(
            model_name='studentexamanswer',
            name='gemini_response',
            field=models.TextField(blank=True, help_text='Raw Gemini response', null=True),
        ),
    ]
