# Generated by Django 4.2.23 on 2025-09-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_merge_20250925_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
