# Generated by Django 4.2.23 on 2025-08-01 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_lesson_date_alter_lesson_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='multiple_choice', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('3', 'Level 3 - Basic'), ('4', 'Level 4 - Intermediate'), ('5', 'Level 5 - Advanced')], max_length=2)),
                ('subject', models.CharField(default='math', max_length=100)),
                ('option_a', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_by_ai', models.BooleanField(default=True)),
                ('modified_by_teacher', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scheduler.document')),
            ],
            options={
                'ordering': ['difficulty_level', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('level_test', 'Level Test'), ('practice_test', 'Practice Test')], max_length=20)),
                ('difficulty_level', models.CharField(choices=[('3', 'Level 3 - Basic'), ('4', 'Level 4 - Intermediate'), ('5', 'Level 5 - Advanced')], max_length=2)),
                ('subject', models.CharField(default='math', max_length=100)),
                ('total_questions', models.IntegerField(default=10)),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.questionbank')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='scheduler.testsession')),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
    ]
