# Generated by Django 4.2.23 on 2025-09-27 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_questionbank_option_a_questionbank_option_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='scheduler.examsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.questionbank')),
            ],
            options={
                'unique_together': {('exam_session', 'question')},
            },
        ),
    ]
