# Generated by Django 4.2.23 on 2025-08-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_questionbank_testsession_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinteraction',
            name='context_used',
            field=models.BooleanField(default=False, help_text='Whether RAG context was used'),
        ),
        migrations.AddField(
            model_name='chatinteraction',
            name='sources_count',
            field=models.IntegerField(default=0, help_text='Number of document sources used'),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_content',
            field=models.TextField(blank=True, help_text='Extracted text content for AI processing', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='questions_generated_count',
            field=models.IntegerField(default=0, help_text='Number of questions generated from this document'),
        ),
        migrations.AddField(
            model_name='document',
            name='rag_chunks',
            field=models.TextField(blank=True, help_text='JSON stored RAG chunks', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='is_generated',
            field=models.BooleanField(default=False, help_text='True if generated by AI'),
        ),
    ]
