# Generated by Django 5.2.7 on 2025-10-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_document_grading_instructions'),
        ('scheduler', '0006_questionattempt'),
    ]

    operations = [
    ]
