# Generated by Django 4.2.23 on 2025-08-08 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_chatinteraction_context_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='test_type',
            field=models.CharField(choices=[('level_test', 'Level Test'), ('practice_test', 'Practice Test'), ('exam', 'Exam')], max_length=20),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(default='math', max_length=100)),
                ('difficulty_level', models.CharField(blank=True, choices=[('3', 'Level 3 - Basic'), ('4', 'Level 4 - Intermediate'), ('5', 'Level 5 - Advanced')], max_length=2, null=True)),
                ('total_questions', models.IntegerField(default=10)),
                ('exam_time_limit_minutes', models.IntegerField(blank=True, null=True)),
                ('per_question_time_seconds', models.IntegerField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('selection_rules', models.TextField(blank=True, help_text='Optional JSON rules for sampling questions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='assigned_exams', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(blank=True, related_name='exams', to='scheduler.questionbank')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testsession',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scheduler.exam'),
        ),
    ]
