# Generated by Django 4.2.23 on 2025-10-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_merge_20251014_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scheduler.exam'),
        ),
    ]
