# Generated by Django 4.2.23 on 2025-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_testsession_test_type_exam_testsession_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='selection_rules',
        ),
        migrations.AddField(
            model_name='exam',
            name='selection_rules_text',
            field=models.TextField(blank=True, help_text='Optional JSON rules for sampling questions', null=True),
        ),
    ]
