# Generated by Django 4.2.23 on 2025-08-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_remove_exam_selection_rules_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='selection_rules_text',
            new_name='selection_rules',
        ),
    ]
