# Generated by Django 4.2.23 on 2025-08-09 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_topic_alter_questionbank_is_generated_examsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, help_text='When the exam should become available to students', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='When the exam should no longer be available', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_student', models.ForeignKey(blank=True, help_text='Optional student assignment for personalized exams', limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exam_configs', to=settings.AUTH_USER_MODEL)),
                ('exam_session', models.ForeignKey(help_text='The exam session this configuration is based on', on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='scheduler.examsession')),
                ('teacher', models.ForeignKey(help_text='Teacher who created this configuration', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_exam_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamConfigQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(help_text='Sequential order of questions starting from 1')),
                ('exam_config', models.ForeignKey(help_text='The exam configuration this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='config_questions', to='scheduler.examconfig')),
                ('question', models.ForeignKey(help_text='The question to include in this exam', on_delete=django.db.models.deletion.CASCADE, related_name='config_questions', to='scheduler.questionbank')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('exam_config', 'order_index'), ('exam_config', 'question')},
            },
        ),
    ]
