# Generated by Django 4.2.23 on 2025-08-09 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_examconfig_examconfigquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_text',
            field=models.TextField(default=0, help_text="Student's answer text"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='scheduler.examsession'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='interaction_log',
            field=models.TextField(blank=True, default='{}', help_text='JSON string of extra metadata from conversation/chat flow'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Student who provided this answer', limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When the answer was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student_answer',
            field=models.TextField(blank=True, help_text='Legacy field - use answer_text instead', null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='test_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='scheduler.testsession'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('test_session__isnull', False)), fields=('test_session', 'question', 'student'), name='unique_test_session_answer'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('exam_session__isnull', False)), fields=('exam_session', 'question', 'student'), name='unique_exam_session_answer'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('exam_session__isnull', True), ('test_session__isnull', False)), models.Q(('exam_session__isnull', False), ('test_session__isnull', True)), _connector='OR'), name='one_session_type_required'),
        ),
    ]
