# Generated by Django 4.2.23 on 2025-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_examconfig_examconfigquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='current_level_processing',
            field=models.CharField(blank=True, help_text='Currently processing difficulty level', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Last processing heartbeat timestamp', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_progress',
            field=models.TextField(blank=True, default='{}', help_text='Processing progress per difficulty level (JSON string)'),
        ),
        migrations.AddField(
            model_name='document',
            name='total_levels',
            field=models.IntegerField(default=3, help_text='Total number of difficulty levels to process'),
        ),
    ]
