# Generated by Django 4.2.23 on 2025-08-09 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_alter_studentanswer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(help_text='Which attempt this is (1, 2, 3, etc.)')),
                ('answer_text', models.TextField(help_text="The student's answer for this attempt")),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this attempt was correct')),
                ('hint_provided', models.TextField(blank=True, help_text='Hint provided by OLAMA after incorrect answer', null=True)),
                ('olama_context', models.TextField(default='{}', help_text='JSON context for OLAMA conversation')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='Time taken for this attempt', null=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='scheduler.examsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='scheduler.questionbank')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('exam_session', 'student', 'question', 'attempt_number')},
            },
        ),
    ]
