# Generated by Django 4.2.23 on 2025-08-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_document_current_level_processing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='subject',
            field=models.CharField(choices=[('algorithms', 'Algorithms'), ('data_structures', 'Data Structures'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('complexity_analysis', 'Complexity Analysis'), ('programming', 'Programming Concepts')], default='algorithms', max_length=50),
        ),
    ]
