# Generated by Django 4.2.23 on 2025-08-09 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_examanswerattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.IntegerField(default=0, help_text='Total number of attempts made')),
                ('is_correct', models.BooleanField(default=False, help_text='Whether question was answered correctly')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether question is completed (correct or max attempts reached)')),
                ('final_answer', models.TextField(blank=True, help_text='Final answer provided by student', null=True)),
                ('grading_confidence', models.FloatField(default=0.0, help_text='Confidence score from grading algorithm')),
                ('grading_method', models.CharField(default='text', help_text='Method used for grading (mcq, numeric, text, etc.)', max_length=50)),
                ('first_attempt_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('completion_time_seconds', models.IntegerField(blank=True, help_text='Total time spent on this question', null=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_states', to='scheduler.examsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_states', to='scheduler.questionbank')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_question_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_attempt_at'],
                'indexes': [models.Index(fields=['exam_session', 'student'], name='scheduler_e_exam_se_274e5a_idx'), models.Index(fields=['exam_session', 'is_completed'], name='scheduler_e_exam_se_683f8d_idx')],
                'unique_together': {('exam_session', 'student', 'question')},
            },
        ),
    ]
