# Generated by Django 4.2.23 on 2025-08-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_alter_questionbank_subject'),
        ('scheduler', '0018_examquestionstate'),
    ]

    operations = [
    ]
