# Generated by Django 4.2.23 on 2025-08-28 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_merge_20250822_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('3', 'Basic'), ('4', 'Intermediate'), ('5', 'Advanced')], max_length=2)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('time_taken_seconds', models.IntegerField()),
                ('percentage_score', models.FloatField()),
                ('assessed_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Elementary', 'Elementary'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('questions_used', models.TextField(blank=True, help_text='JSON array of question IDs used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ExamQuestionState',
        ),
    ]
