# Generated by Django 4.2.23 on 2025-08-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_merge_20250822_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='current_question_index',
            field=models.IntegerField(default=0, help_text='Current position in question sequence'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether the session is completed'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_metadata',
            field=models.TextField(default='{}', help_text='Additional session data as JSON string'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_questions',
            field=models.IntegerField(default=0, help_text='Total questions in this session'),
        ),
        migrations.DeleteModel(
            name='ExamQuestionState',
        ),
    ]
