# Generated by Django 4.2.23 on 2025-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_add_document_learning_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='notes',
            field=models.TextField(blank=True, help_text='JSON data for exam questions and progress', null=True),
        ),
    ]
