# Generated by Django 4.2.23 on 2025-08-28 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_studenttestresult_delete_examquestionstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='option_d',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='expected_approach',
            field=models.TextField(blank=True, help_text='Expected solution approach or algorithm', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='hints',
            field=models.TextField(blank=True, help_text='AI-generated hints for struggling students', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='key_concepts',
            field=models.TextField(blank=True, help_text='Key concepts the question tests', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='sample_solution',
            field=models.TextField(blank=True, help_text='Sample solution or pseudocode', null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(default='algorithms', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('open_ended', 'Open Ended'), ('coding', 'Coding Problem'), ('algorithm_design', 'Algorithm Design'), ('complexity_analysis', 'Complexity Analysis')], default='open_ended', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='subject',
            field=models.CharField(choices=[('algorithms', 'Algorithms'), ('data_structures', 'Data Structures'), ('sorting', 'Sorting Algorithms'), ('searching', 'Searching Algorithms'), ('graph_algorithms', 'Graph Algorithms'), ('dynamic_programming', 'Dynamic Programming'), ('greedy_algorithms', 'Greedy Algorithms'), ('complexity_analysis', 'Complexity Analysis'), ('recursion', 'Recursion'), ('divide_conquer', 'Divide and Conquer')], default='algorithms', max_length=50),
        ),
        migrations.AlterField(
            model_name='studenttestresult',
            name='assessed_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studenttestresult',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='subject',
            field=models.CharField(default='algorithms', max_length=100),
        ),
        migrations.CreateModel(
            name='TestHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_text', models.TextField(help_text='AI-generated hint text')),
                ('hint_level', models.IntegerField(default=1, help_text='Progressive hint level (1=basic, 2=medium, 3=detailed)')),
                ('student_input', models.TextField(help_text="Student's input that triggered the hint")),
                ('context_used', models.TextField(blank=True, help_text='Document context used for hint', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_helpful', models.BooleanField(blank=True, help_text='Student feedback on hint helpfulness', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.questionbank')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='scheduler.testsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
