# Generated by Django 4.2.23 on 2025-08-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_remove_questionbank_option_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='option_a',
            field=models.TextField(blank=True, help_text='Option A for multiple choice questions', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_b',
            field=models.TextField(blank=True, help_text='Option B for multiple choice questions', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_c',
            field=models.TextField(blank=True, help_text='Option C for multiple choice questions', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_d',
            field=models.TextField(blank=True, help_text='Option D for multiple choice questions', null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('open_ended', 'Open Ended'), ('coding', 'Coding Problem'), ('algorithm_design', 'Algorithm Design'), ('complexity_analysis', 'Complexity Analysis'), ('multiple_choice', 'Multiple Choice')], default='open_ended', max_length=20),
        ),
    ]
